services:
  php-apache:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        NODE_VERSION: ${NODE_VERSION}
    container_name: ezhpo-php
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${PROJECTS_ROOT}:/var/www
      - ${APP_VHOST_DIR}:/etc/apache2/sites-available
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - ezhpo-network
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    platform: linux/amd64
    container_name: ezhpo-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ezhpo-network

networks:
  ezhpo-network:
    driver: bridge

volumes:
  db-data: