services:
  traefik:
    image: traefik:v3.5
    container_name: ezhpo-traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true" 
      - "--api.dashboard=true" 
    ports:
      - "80:80" 
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

  php-apache:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        APP_VHOST_DIR: ${APP_VHOST_DIR}
        UID: ${UID}
        GID: ${GID}
    container_name: ezhpo-php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ezhpo.rule=Host(`ezhpo.localhost`)"
      - "traefik.http.routers.ezhpo.entrypoints=web"
    volumes:
      - ${PROJECT_DIR}:/var/www/ezhpo
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: ezhpo-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data: